name: camphor_forest
description: "SWU Student Toolbox"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0+2

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  flutter_launcher_icons: ^0.14.4
  go_router: ^8.0.3
  riverpod_annotation: ^2.6.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.0
  flutter_platform_widgets: ^9.0.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  http: ^1.4.0
  uuid: ^4.2.1
  image_picker: ^1.0.8
  image_cropper: ^8.0.2
  image: ^4.2.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  package_info_plus: ^8.0.0
  syncfusion_flutter_calendar: ^30.1.38
  url_launcher: ^6.3.1
  layout: ^1.0.5
  font_awesome_flutter: ^10.9.0
  flex_color_picker: ^3.7.1
  permission_handler: ^11.3.1
  gal: ^2.3.0
  crypto: ^3.0.5
  path_provider: ^2.1.5
  fl_chart: ^0.69.0
  webview_flutter: ^4.7.0
  flutter_platform_alert: ^0.8.0
  flutter_baidu_mapapi_map: ^3.9.5
  flutter_baidu_mapapi_base: ^3.9.5
  apple_maps_flutter: ^1.4.0
  map_launcher: ^4.4.2
  geolocator: ^13.0.1
  sensors_plus: ^6.0.1
  web_socket_channel: ^3.0.3
  home_widget: ^0.8.1
  dynamic_color: ^1.7.0
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/bus/
    - assets/icons/swulogo.svg
    - assets/splash_logo.png
    - lib/pages/login/userAgreement.txt
    - files/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/swulogo.jpg"
  adaptive_icon_background: "#ffffff"
  assets:
    - assets/icons/

flutter_native_splash:
  color: "#ffffff" # 白色背景
  background_image: assets/splash_background.png # 你的主图

  android_12:
    image: "assets/splash_logo.png"
    color: "#ffffff"
    branding: assets/brand_logo.png

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #       - asset: assets/fonts/Roboto-Light.ttf
